# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='课程名称')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='课程编号')),
                ('intro', models.TextField(max_length=140, verbose_name='课程简介')),
                ('credit', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=None, verbose_name='学分')),
                ('grade_class', models.ManyToManyField(blank=True, related_name='course_class', to='user_management.GradeInfo', verbose_name='学生')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.Teacher', verbose_name='授课教师')),
            ],
            options={
                'verbose_name_plural': '课程',
                'verbose_name': '课程',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5, verbose_name='成绩')),
                ('credit', models.IntegerField(verbose_name='所获学分')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseAndScore.Course', verbose_name='课程名称')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name_plural': '学生成绩',
                'verbose_name': '学生成绩',
            },
        ),
    ]
