# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='课程名称')),
                ('number', models.CharField(max_length=10, verbose_name='课程编号')),
                ('intro', models.CharField(max_length=140, verbose_name='课程简介')),
                ('credit', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=None, verbose_name='学分')),
                ('student', models.ManyToManyField(related_name='course_s', to='user_management.Student', verbose_name='学生')),
                ('teacher', models.ManyToManyField(related_name='course_t', to='user_management.Teacher', verbose_name='授课教师')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5, verbose_name='成绩')),
                ('credit', models.IntegerField(verbose_name='所获学分')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseAndScore.Course', verbose_name='课程名称')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Student', verbose_name='学生')),
            ],
        ),
    ]
