# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '校园资讯',
                'verbose_name_plural': '校园资讯',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, choices=[(1, '大一'), (2, '大二'), (3, '大三'), (4, '大四')], default=None, verbose_name='年级')),
                ('the_class', models.CharField(blank=True, max_length=30, verbose_name='班级')),
                ('department', models.IntegerField(blank=True, choices=[(1, '中文系'), (2, '政法系'), (3, '外语系'), (4, '数学系'), (5, '物理系'), (6, '化学系'), (7, '生物系'), (8, '音乐系'), (9, '美术系'), (10, '体育系'), (11, '计算机系')], default=None, verbose_name='系别')),
            ],
            options={
                'verbose_name': '系别班级',
                'verbose_name_plural': '系别班级',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=15, unique=True, verbose_name='帐号')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=None, verbose_name='姓别')),
                ('phone_num', models.CharField(blank=True, max_length=12, verbose_name='联系电话')),
                ('address', models.TextField(blank=True, max_length=140, verbose_name='住址')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.GradeInfo', verbose_name='年级班级')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=15, unique=True, verbose_name='帐号')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=None, verbose_name='姓别')),
                ('department', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='系别')),
                ('phone_num', models.CharField(blank=True, max_length=12, verbose_name='联系电话')),
                ('address', models.TextField(blank=True, max_length=140, verbose_name='住址')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
    ]
