# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=15, verbose_name='帐号')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=None, verbose_name='姓别')),
                ('grade', models.CharField(max_length=30, verbose_name='年级')),
                ('the_class', models.CharField(max_length=30, verbose_name='班级')),
                ('department', models.CharField(max_length=30, verbose_name='系别')),
                ('phone_num', models.CharField(blank=True, max_length=12, verbose_name='联系电话')),
                ('address', models.TextField(blank=True, max_length=140, verbose_name='住址')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=15, verbose_name='帐号')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=None, verbose_name='姓别')),
                ('grade', models.CharField(max_length=30, verbose_name='年级')),
                ('the_class', models.CharField(max_length=30, verbose_name='班级')),
                ('department', models.CharField(max_length=30, verbose_name='系别')),
                ('phone_num', models.CharField(blank=True, max_length=12, verbose_name='联系电话')),
                ('address', models.TextField(blank=True, max_length=140, verbose_name='住址')),
            ],
        ),
    ]
