# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='发布时间'),
        ),
    ]
