# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20170420_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campusinfo',
            options={'ordering': ['-timestamp'], 'verbose_name': '校园资讯', 'verbose_name_plural': '校园资讯'},
        ),
    ]
